database:
  host: localhost
  port: 5432
  user: username
  pass: password
  name: live_stream

redis:
  host: localhost
  port: 6379
  user: username
  pass: password

web:
  port: 8787

file_storage:
  root_folder: ./tmp
  thumbnail_folder: ./tmp/thumbnail/
  avatar_folder: ./tmp/avatar/
  live_folder: ./tmp/recordings/live/

api_file:
  url: http://localhost:8787

stream_server:
  http_url: http://localhost:8090
  rtmp_url: rtmp://localhost:1935/live
  hls_url: http://localhost:7002/live

auth:
  secret_key: live&^stream^%2024@

mail:
  email: username@gmail.com
  password: alkdjklanbvudjehje
  host: smtp.gmail.com
  port: 587

2fa_auth:
  issuer: live-stream.org