database:
  host: localhost
  port: 5432
  user: username
  pass: password
  name: live_stream

redis:
  host: localhost
  port: 6379
  user: username
  pass: password

web:
  port: 8787

file_storage:
  thumbnail_folder: ./tmp

stream_server:
  http_url: http://localhost:8090
  rtmp_url: rtmp://localhost:1935/live
  hls_url: http://localhost:7002/live

auth:
  secret_key: live&^stream^%2024@

mail:
  email: username@gmail.com
  password: alkdjklanbvudjehje
  host: smtp.gmail.com
  port: 587