database:
  host: localhost
  port: 5432
  user: postgres
  pass: postgres
  name: dbyoumi

redis:
  host: localhost
  port: 6379
  user: username
  pass: password

web:
  port: 8787
  salt_key: secret_key
