services:
  postgres:
    image: postgres:16.2-alpine
    networks:
      - bank-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbyoumi
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data

networks:
  bank-network:
    name: bank-network

volumes:
  data-volume: